variables:
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates' 

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.6.5
    endpoint: 'GitHub (ESFA)'

jobs:

#Build and test resources
- template: AzureDevOpsTemplates/Build/dfc-arm-build.yml@dfc-devops
  parameters:
    ArmTemplateRoot: $(ArmTemplateRoot)

#Publish templates
- job: BuildDotNetCore
  displayName: Build-DotNetCore
  pool:
    name: DAS - Continuous Deployment

  steps:
   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: Azure'
     inputs:
       pathtoPublish: $(build.artifactstagingdirectory)
       artifactName: Azure
       publishLocation: container